### ISSUE TITLE
Pet castbar becomes player castbar after leaving vehicle

### ISSUE THREAD

**Issue by solumg** [Sticklord/oUF_Abu#2]
Have a pet out. Use a vehicle. Jump out. Now when ever you cast a spell, the petcastbar also shows up as your own cast bar(like having double castbars). Sometimes the Pet unitframe also becomes the player frame.

**Comment by Sticklord** [comment]
Got some bored, so wanted to try to update this! I think i fixed these bugs now.

**Comment by Likusmydikus** [comment]
Actually, issue I submitted was duplicate of this one. It still persists.
